[package]

name = "netrc"
version = "0.1.0"
authors = ["Paul Woolcock <paul@woolcock.us>", "Jimmy Lu <gongchuo.lu@gmail.com"]
repository = "https://github.com/pwoolcoc/netrc-rs"
license = "MIT"
description = "Parses and encapsulates the `netrc` file format"

