[package]

name = "netrc"
version = "0.4.0"
authors = ["Jimmy Lu <gongchuo.lu@gmail.com"]
repository = "https://github.com/pwoolcoc/netrc-rs"
license = "MIT"
description = "Parses and encapsulates the `netrc` file format"
